/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e0d84178-054b-4566-b4d3-47ccedba416b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_PChaOKX8E",
    "aws_user_pools_web_client_id": "28psji9lvrrss9lmtgpekmskmd",
    "oauth": {}
};


export default awsmobile;
